/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_herbwen_myjnitest_MainActivity */

#ifndef _Included_com_herbwen_myjnitest_MainActivity
#define _Included_com_herbwen_myjnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_herbwen_myjnitest_MainActivity
 * Method:    getFirString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_herbwen_myjnitest_MainActivity_getFirString
  (JNIEnv *, jobject);

/*
 * Class:     com_herbwen_myjnitest_MainActivity
 * Method:    getSecString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_herbwen_myjnitest_MainActivity_getSecString
  (JNIEnv *, jclass);

/*
 * Class:     com_herbwen_myjnitest_MainActivity
 * Method:    getThirdString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_herbwen_myjnitest_MainActivity_getThirdString
  (JNIEnv *, jobject);

/*
 * Class:     com_herbwen_myjnitest_MainActivity
 * Method:    getCores
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_herbwen_myjnitest_MainActivity_getCores
  (JNIEnv *, jobject);

/*
 * Class:     com_herbwen_myjnitest_MainActivity
 * Method:    bindToCPU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_herbwen_myjnitest_MainActivity_bindToCPU
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
